#!/bin/bash

zip -r boundsoff_page-builder-live-preview-1.0.0.zip ./ \
  -x './.git' \
  -x './page-builder-types/' \
  -x './**/.babelrc.js' \
  -x './**/babel/' \
  -x './**/*.js.map' \
  -x '.gitignore' \
  -x '.gitmodules' \
  -x 'create-package' \
  -x 'DEPLOY.md'
